version: '3.9'
services:
  backend:
    build: .
    command: bash -c "python manage.py makemigrations api & python manage.py migrate & gunicorn -w 3 config.wsgi --bind 0.0.0.0:8000 --timeout 600"
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/app
    ports:
      - "8000:8000"